apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: igp-voting-app
  name: igp-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: igp-voting-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: igp-voting-app
    spec:
      containers:
      - image: oadetiba/igp-voting-app:latest
        name: igp-voting-app
        resources: {}
status: {}
# kubectl create deployment hello-world --image=oadetiba/imageid:1.0 --dry-run=client -o yaml > hello-world.yaml