apiVersion: app/v1
Kind: apiVersion: apps/v1
kind: Deployment
metadata:
  name:  igp-voting-app
  namespace: default
  labels:
    app:  igp-voting-app
spec:
  selector:
    matchLabels:
      app: igp-voting-app
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  igp-voting-app
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  igp-voting-app
        image:  oadetiba/igp-voting-app:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env:
        #- name: DB_HOST
        #  valueFrom:
        #    configMapKeyRef:
        #      name: igp-voting-app
        #      key: DB_HOST
        ports:
        - containerPort:  80
          name:  igp-voting-app
        #volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/America/Vancouver
      restartPolicy: Always