apiVersion: v1
kind: Service
metadata:
  name: igp-voting-app-svc
  namespace: default
spec:
  selector:
    app: igp-voting-app
  type: NodePort
  ports:
  - name: webapps
    port: 80
    targetPort: 8888
    protocol: TCP
    nodePort: 30085